### ISSUE TITLE
Support npm v3+ non nested node_modules

### ISSUE THREAD

**Issue by hthetiot** [montagejs/mr#104]
Origin of non nested node_modules in npm:
- https://github.com/nodejs/node-v0.x-archive/issues/6960

Other possible workaround:
- https://github.com/npm/npm/issues/9809

**Comment by hthetiot** [comment]
@marchant the problem is that their is no way to make the difference from a relative module and a absolute module.

Currently, on master branch, require() is loading the module in the "node_modules" of the current module and process module with or without "./" the same way my removing "./"

Meaning from a module "a" calling require("b") or require("./b") will result "node_modules/a/node_modules/b".

The issue with this is that if you need to load a module that is not a sub-module you need to specify the full path in order to support npm 3+ . (Example weak-map in collections)

What I'm proposing is to match the AMD standard, and load module as submodule only if relative.

Example:
1. calling require("./b")  from module "a" will result "node_modules/a/node_modules/b".
2. calling require("b") from module "a" will result "node_modules/b".

**Comment by kriskowal** [comment]
When I rewrote Mr to support extension modules (https://github.com/gutentags/system/blob/master/common-system.js), I set it up to distinguish "internal" and "external", so internal/externalRedirects, internal/externalModules, etc.

The rules you cite are not correct nor consistent with Node/npm. They should be spelled:

1. require("./b") is an internal module and will resolve to a file in the same package, `b.js`
2. require("b") is an external module and will resolve to the root of the "b" package, `node_modules/b`, following the "main" entry in package.json or falling back to "index.js".

The distinction of "external" remains important, but the package location semantics vary depending on who wrote package.json. A hand crafted package.json implies only that the shallow dependencies must be in the root node_modules and can be nowhere else, regardless of which package manager you use to populate node_modules. Various package managers only vary in the semantics they use to reparent their shallow dependencies up the tree.

- In yarn, for example, you are guaranteed that all packages are in the root node_modules.
- In npm 3, you are guaranteed that they are elevated as high as they can go without introducing a version conflict, so you need both to know that your package was droppped by npm 3 and also be aware of semver and walk up the tree.
- In npm 2, the existing semantics work most of the time but they are not perfect.
