### ISSUE TITLE
Commenting out require does not prevent file from loading

### ISSUE THREAD

**Issue by toji** [montagejs/mr#12]
If you comment out a `require()` line, like so:

```
//var SomeObj = require('filePath').SomeObj;
```

`'filePath.js'` will still be loaded by the browser. If the file path does not exist you will get a 404 error that prevents the rest of the page from loading. Commented out lines should not have any effect on the page execution.

**Comment by hthetiot** [comment]
378cabb338e9065489b3731c0f5752ab2ceb66fa
