### ISSUE TITLE
Create module to create mock requires

### ISSUE THREAD

**Issue by Stuk** [montagejs/mr#35]
Related to the sandbox #22 (and perhaps replacing it) it would be useful to make a mock require that does not go to the network at all, and has all of it's modules/module text injected.

API sketch:

``` javascript
var mock = require("mr/mock");

var mockRequire = mock(
   exports, // mapping from module ids to export objects
   moduleTexts, // mapping from module ids to the text of the module (so module dependencies can still be setup by Mr
   require.config, // require config object, to pick up mappings/the loader/compiler chain
   doesPassThru // ? boolean to toggle going to network if the module isn't injected
);
```

**Comment by hthetiot** [comment]
@cdebost I cant add you here properly yet.
Please @marchant can you allow me to controls teams contents.

**Comment by hthetiot** [comment]
- https://github.com/montagejs/mr/blob/master/test/spec/inject/program.js

**Comment by hthetiot** [comment]
See #116
